sudo: false
language: node_js
node_js:
  - stable

cache:
  bundle: true
  directories:
    - ~/.npm
    - node_modules

install:
  - npm install

jobs:
  include:
#    - stage: Document deploy
#      allow_failure: true
#      script: picidae build -f
#      deploy:
#        nodejs: stable
#        provider: pages
#        skip_cleanup: true
#        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
#        local_dir: public

    - stage: Unit testing
      script: npm test

#    - stage: E2E testing
#      script: npm run test:cy:ci $CYPRESS_RECORD_KEY

        # repo: $GH_REF
